<html>
<head>
<head>
	<title>asdf</title>
	<link rel="stylesheet" type="text/css" href="css/default.css" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Roboto:300,300i,400,400i,700,700i" />
	<script src="https://use.fontawesome.com/4ac9f53b4f.js"></script>
</head>
<body class="ThemeLight">

<div class="PageContain Header"><section>
	<div class="Logo">[ProjectLogo]</div>
	<ul class="Nav">
		<li><a href="">Namespaces</a></li>
		<li><a href="">Classes</a></li>
		<li><a href="">Functions</a></li>
		<li><a href="">Files</a></li>
	</ul>
	<hr class="FloatClear" />

	<div class="Intro">
		<h1>ExampleAppThing</h1>
		<p>This is an example class that does nothing other than use a lot of
		code so we have something to render in the documentation.</p>
	</div>
</section></div>

<div class="PageContain Main"><section>
	<div class="Content">

<dl class="Lang Class">
	<dd class="Info">
		<span class="LangTag DataType">Class</span>
		<span class="LangTag DataType">Extends <span>ExampleAppGenericItem</span></span>
		<span class="LangTag DataType">Implements <span>ExampleAppUsableItem</span></span>
	</dd>
	<dd class="Comment">
		This class defines the thing we can use to do the stuff. It is the
		main object type that will be interacted with in this application.
	</dd>
</dl>

<h2 class="Heading">Properties</h2>
<dl class="Lang Property">
	<dd class="Info">
		<span class="LangTag Access">Property</span>
		<span class="LangTag DataType">Protected</span>
		<span class="LangTag DataType">String</span>
	</dd>
	<dt class="Name">Colour</dt>
	<dd class="Comment">Define what colour we should use in this layout.</dd>
</dl>

<h2 class="Heading">Methods</h2>
<dl class="Lang Property">
	<dd class="Info">
		<span class="LangTag Access">Method</span>
		<span class="LangTag DataType">Public</span>
		<span class="LangTag DataType">Getter <span>Colour</span></span>
	</dd>
	<dt class="Name">GetColour(<span class="LangTag DataType">Void</span>):</dt>
	<dd class="Info">
		<span class="LangTag DataType">String</span>
	</dd>
	<dd class="Comment">Define what colour we should use in this layout.</dd>
</dl>
<dl class="Lang Property">
	<dd class="Info">
		<span class="LangTag Access">Method</span>
		<span class="LangTag DataType">Public</span>
		<span class="LangTag DataType">Setter <span>Colour</span></span>
	</dd>
	<dt class="Name">SetColour(<span class="LangTag DataType">String <span>NewColour</span></span>):</dt>
	<dd class="Info">
		<span class="LangTag DataType">Self</span>
	</dd>
	<dd class="Comment">Define what colour we should use in this layout.</dd>
</dl>

	</div>
	<div class="Sidebar">
		<dl class="ItemList">
			<dt>ExampleAppThing</dt>
			<dd><a href="">Constants <span>0</span></a></dd>
			<dd><a href="">Properties <span>1</span></a></dd>
			<dd><a href="">Methods <span>2</span></a></dd>
		</dl>
		<dl class="ItemList">
			<dt>Extends</dt>
			<dd><a href=""><i class="fa fa-long-arrow-up fa-fw"></i> ExampleAppGenericItem</a></dd>
			<dd><a href=""><i class="fa fa-long-arrow-up fa-fw"></i> ExampleAppAbstractItem</a></dd>
			<dd><a href=""><i class="fa fa-long-arrow-up fa-fw"></i> OverlyAbstractedObject</a></dd>
		</dl>
		<dl class="ItemList">
			<dt>Implements</dt>
			<dd><a href=""><i class="fa fa-long-arrow-up fa-fw"></i> ExampleAppUsableItem</a></dd>
		</dl>
		<dl class="ItemList">
			<dt>Used By</dt>
			<dd><a href=""><i class="fa fa-long-arrow-right fa-fw"></i> VerySpecificThing</a></dd>
		</dl>
	</div>

	<hr class="FloatClear" />
</section></div>

</body>
</head>
</html>